"""Cisco renderers backed by the shared IOS syntax implementation."""

from app.models.device import Device
from app.renderers.base import ConfigRenderer
from app.renderers.cisco_common import render_cisco_config


class CiscoIOSRenderer(ConfigRenderer):
    file_extension = "cfg"
    target_platform = "Cisco IOS"
    target_syntax_notes = (
        "Rendered against classic IOS CLI syntax. Verify feature availability on "
        "your specific IOS train/version."
    )

    def render(self, device: Device) -> str:
        return render_cisco_config(device, "! Generated by NetConfig Intelligence (Cisco IOS)")


class CiscoIOSXERenderer(ConfigRenderer):
    file_extension = "cfg"
    target_platform = "Cisco IOS-XE"
    target_syntax_notes = (
        "Rendered against IOS-XE CLI syntax, which is largely compatible with classic "
        "IOS for the features modeled here. Verify against your target IOS-XE release."
    )

    def render(self, device: Device) -> str:
        return render_cisco_config(device, "! Generated by NetConfig Intelligence (Cisco IOS-XE)")
