from __future__ import annotations

from app.models.device import Device
from app.renderers.base import ConfigRenderer


class MikroTikRouterOSRenderer(ConfigRenderer):
    file_extension = "rsc"
    target_platform = "MikroTik RouterOS"
    target_syntax_notes = (
        "Rendered against current RouterOS v6/v7 command syntax. Some commands "
        "(e.g. bridge handling) differ between the v6 and v7 branches - review "
        "before importing."
    )

    def render(self, device: Device) -> str:
        lines: list[str] = ["# Generated by NetConfig Intelligence (MikroTik RouterOS)"]

        if device.hostname:
            lines.append("/system identity")
            lines.append(f"set name={device.hostname}")

        if device.interfaces:
            for iface in device.interfaces:
                lines.append("/interface ethernet")
                comment = f" comment=\"{iface.description}\"" if iface.description else ""
                disabled = " disabled=yes" if not iface.enabled else ""
                lines.append(f"set [ find default-name={iface.name} ]{comment}{disabled}")

        for vlan in device.vlans:
            parent = vlan.interfaces[0] if vlan.interfaces else "bridge1"
            lines.append("/interface vlan")
            lines.append(f"add name={vlan.name or f'vlan{vlan.id}'} vlan-id={vlan.id} interface={parent}")

        if any(iface.ipv4 for iface in device.interfaces):
            lines.append("/ip address")
            for iface in device.interfaces:
                for ipv4 in iface.ipv4:
                    lines.append(
                        f"add address={ipv4.address}/{ipv4.prefix_length} interface={iface.name}"
                    )

        if device.routing.static_routes:
            lines.append("/ip route")
            for route in device.routing.static_routes:
                gw = route.next_hop or route.interface or ""
                distance = f" distance={route.metric}" if route.metric is not None else ""
                lines.append(
                    f"add dst-address={route.network}/{route.prefix_length} gateway={gw}{distance}"
                )

        filter_acl = next((a for a in device.acls if a.kind == "firewall_filter"), None)
        if filter_acl and filter_acl.entries:
            lines.append("/ip firewall filter")
            for entry in filter_acl.entries:
                action = "accept" if entry.action == "permit" else "drop"
                lines.append(
                    f"add chain=input action={action} protocol={entry.protocol} "
                    f"src-address={entry.source} dst-address={entry.destination}"
                )

        if device.nat_rules:
            lines.append("/ip firewall nat")
            for nat in device.nat_rules:
                out_if = f" out-interface={nat.interface}" if nat.interface else ""
                lines.append(f"add chain=srcnat action={nat.kind}{out_if}")

        if device.dhcp_pools:
            lines.append("/ip pool")
            for pool in device.dhcp_pools:
                if pool.range_start and pool.range_end:
                    lines.append(f"add name={pool.name}_pool ranges={pool.range_start}-{pool.range_end}")
            lines.append("/ip dhcp-server")
            for pool in device.dhcp_pools:
                lines.append(f"add address-pool={pool.name}_pool interface=bridge1 name={pool.name}")
            lines.append("/ip dhcp-server network")
            for pool in device.dhcp_pools:
                if pool.network and pool.prefix_length:
                    gw = f" gateway={pool.gateway}" if pool.gateway else ""
                    dns = f" dns-server={','.join(pool.dns_servers)}" if pool.dns_servers else ""
                    lines.append(
                        f"add address={pool.network}/{pool.prefix_length}{gw}{dns}"
                    )

        if device.dns_servers:
            lines.append("/ip dns")
            lines.append(f"set servers={','.join(device.dns_servers)}")

        if device.management:
            lines.append("/ip service")
            for svc in device.management:
                disabled = "no" if svc.enabled else "yes"
                addr = f" address={','.join(svc.allowed_sources)}" if svc.allowed_sources else ""
                lines.append(f"set {svc.name} disabled={disabled}{addr}")

        if device.snmp.communities:
            lines.append("/snmp community")
            for community in device.snmp.communities:
                lines.append(f"add name={community}")

        for user in device.users:
            if user.group == "ppp":
                lines.append("/ppp secret")
                lines.append(f"add name={user.username} password={user.secret_raw} service=any")
            else:
                lines.append("/user")
                group = user.group or "read"
                lines.append(f"add name={user.username} group={group}")

        return "\n".join(lines) + "\n"
